name: Glue ETL CI/CD

on:
    push:
        branches: [ main ]

jobs:
    glue_tl:
        runs-on: unbuntu-latest

        env:
            AWS_REGION: us-east-1
        
        steps:
        - name: Set up Python
          uses: actions/checkout@v3
          
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install deps
          run: |
            pip install -r requirements.txt

        - name: Lint code
          run: |
            flake8 scripts/
            black --check scripts/

        - name: Run tests
          run: |
            pytest tests/

        - name: Upload EYL script & config to S3
          run: |
            aws s3 cp scripts/bank_glue_etl_job.py s3://$S3_BUCKET/scripts/
            aws s3 cp configs/job_params.json s3://$S3_BUCKET/configs/
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_BUCKET: ${{ secrets.S3_BUCKET }}